services:
  rabbitmq:
    container_name: aiwings-rabbitmq
    image: rabbitmq:management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mysql:
    container_name: aiwings-mysql
    image: mysql:8.0.27
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drone_cloud_test
      MYSQL_USER: user
      MYSQL_PASSWORD: mysql

  server:
    container_name: aiwings-server
    build: api-server
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - mysql
    ports:
      - "3080:3080"
    environment:
      FRONTEND_URL: http://localhost:5173
      MYSQL_SERVICE_SERVICE_HOST: mysql
      MYSQL_SERVICE_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: user
      MYSQL_SERVICE_PASSWORD: mysql
      RABBITMQ_SERVICE_SERVICE_HOST: rabbitmq
      RABBITMQ_SERVICE_SERVICE_PORT: 5672
      RABBITMQ_SERVICE_USER: guest
      RABBITMQ_SERVICE_PASSWORD: guest
      JWT_TOKEN_SECRET: littleSecret

  web:
    container_name: aiwings-web
    build: web_ui
    restart: unless-stopped
    ports:
      - "3000:80"
