version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.9.11-management
    restart: always  
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - type: bind
        source: ./rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
  mysql:
    # for mac M1, need to add platform
    platform: linux/x86_64

    image: mysql:8.0.27
    # test
    # command: --default-authentication-plugin=mysql_native_password

    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drone_cloud_test

  backend:
    image: lcy/drone-cloud-backend

    restart: always
    depends_on:
      - rabbitmq
      - mysql
    ports:
      - '3030:3030'
    env_file:
      - ./.docker.env

