services:
  rabbitmq_service:
    container_name: rabbitmq
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_SERVICE_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_SERVICE_PASSWORD}
      # 若未設定，預設使用者名稱和密碼為guest/ guest
      # ${RABBITMQ_SERVICE_USER}來自環境變數.env檔案內容

  mysql_service:
    container_name: mysql
    # # for mac M1, need to add platform
    # platform: linux/x86_64
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: drone_cloud_test
      MYSQL_USER: ${MYSQL_SERVICE_USER}
      MYSQL_PASSWORD: ${MYSQL_SERVICE_PASSWORD}
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)

  backend:
    container_name: back-end
    build: ../api-server
    restart: always
    # 令 docker-compose up backend 時會先建立並啟動服務名rabbitmq和mysql
    depends_on:
      - rabbitmq_service
      - mysql_service
      # rabbitmq_service、mysql_service是前面建立好的服務
    ports:
      - "3080:3080"
    environment:
      # RabbitMQ connection parameters
      RABBITMQ_SERVICE_SERVICE_HOST: ${RABBITMQ_SERVICE_SERVICE_HOST}
      RABBITMQ_SERVICE_SERVICE_PORT: ${RABBITMQ_SERVICE_SERVICE_PORT}
      RABBITMQ_SERVICE_USER: ${RABBITMQ_SERVICE_USER}
      RABBITMQ_SERVICE_PASSWORD: ${RABBITMQ_SERVICE_PASSWORD}
      # MySQL connection parameters
      MYSQL_SERVICE_SERVICE_HOST: ${MYSQL_SERVICE_SERVICE_HOST}
      MYSQL_SERVICE_SERVICE_PORT: ${MYSQL_SERVICE_SERVICE_PORT}
      MYSQL_SERVICE_USER: ${MYSQL_SERVICE_USER}
      MYSQL_SERVICE_PASSWORD: ${MYSQL_SERVICE_PASSWORD}
    # env_file:
    #   - ./.env
    # 透過environment或env_file加入系統環境變數的話，就要到容器中修改系統環境變數，用掛載的話則是容易更改【思考後覺得不必要】
    # 其他容器服務名稱好像要透過系統環境變數，才可被解析成區域IP
    # volumes:
    #   - ./.env.docker:/app/.env

  front_end:
    container_name: front-end
    restart: always
    build: ../web_ui
    ports:
      - "80:80"
      - "443:443"
    environment:
      URL_FRONTEND: ${URL_FRONTEND}
      URL_BACKEND: backend
    # volumes:
    # - ${SSL_folder}:/etc/nginx/ssl/
# -d|detach：在後台運行。此為docker run 命令，屬容器級別
# docker-compose.yml檔案 屬於服務級別
# 若要在後台運行，在docker-compose up 後面加上 -d
