services:
  rabbitmq:
    container_name: aiwings-rabbitmq
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_SERVICE_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_SERVICE_PASSWORD}
      # 若未設定，預設使用者名稱和密碼為guest/ guest
      # ${RABBITMQ_SERVICE_USER}來自環境變數.env檔案內容

  mysql:
    container_name: aiwings-mysql
    # # for mac M1, need to add platform
    # platform: linux/x86_64
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: drone_cloud_test
      MYSQL_USER: ${MYSQL_SERVICE_USER}
      MYSQL_PASSWORD: ${MYSQL_SERVICE_PASSWORD}
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)

  server:
    container_name: aiwings-server
    build: ../api-server
    restart: always
    depends_on:
      - rabbitmq
      - mysql
    ports:
      - "3080:3080"
    environment:
      # RabbitMQ connection parameters
      RABBITMQ_SERVICE_SERVICE_HOST: ${RABBITMQ_SERVICE_SERVICE_HOST}
      RABBITMQ_SERVICE_SERVICE_PORT: ${RABBITMQ_SERVICE_SERVICE_PORT}
      RABBITMQ_SERVICE_USER: ${RABBITMQ_SERVICE_USER}
      RABBITMQ_SERVICE_PASSWORD: ${RABBITMQ_SERVICE_PASSWORD}
      # MySQL connection parameters
      MYSQL_SERVICE_SERVICE_HOST: ${MYSQL_SERVICE_SERVICE_HOST}
      MYSQL_SERVICE_SERVICE_PORT: ${MYSQL_SERVICE_SERVICE_PORT}
      MYSQL_SERVICE_USER: ${MYSQL_SERVICE_USER}
      MYSQL_SERVICE_PASSWORD: ${MYSQL_SERVICE_PASSWORD}
    # env_file:
    #   - ./.env
    # 透過environment或env_file加入系統環境變數的話，就要到容器中修改系統環境變數，用掛載的話則是容易更改【思考後覺得不必要】
    # 其他容器服務名稱好像要透過系統環境變數，才可被解析成區域IP
    # volumes:
    #   - ./.env.docker:/app/.env

  web:
    container_name: aiwings-web
    build: ../web_ui
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      URL_FRONTEND: localhost
      URL_BACKEND: server
    # volumes:
    # - ${SSL_folder}:/etc/nginx/ssl/
